#### Exercise 1: NumPy array Indexing/Slicing

• 1.1) In this exercise, we will use the iris dataset. Load
the "iris.csv" using the appropriate method for this file
type (use the new functions from the package)'''



In [20]:
import sys
import os
import numpy as np
import pandas as pd
sys.path.append("/Users/utilizador/Documents/GitHub/si/src")

from si.data.dataset import Dataset
from si.io.csv_file import read_csv
from si.io.data_file import *

In [24]:
# Load the iris dataset
Path= "/Users/utilizador/Documents/GitHub/si/datasets/iris/"
data = read_csv(Path + "iris.csv", sep=",", label=True)
shape_= Dataset.shape(data)
has_label= Dataset.has_label(data)
get_classes= Dataset.get_classes(data)
print(shape_, has_label, get_classes)


(150, 4) True ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


1.2) Select the penultimate independent variable.
What is the dimension of the resulting array?

In [25]:
Penultimate=data.X[:,-2]
print("Dimension:",Penultimate.shape[0])

Dimension: 150


1.3) Select the last 10 samples from the iris dataset.
What is the mean of the last 10 samples for each
independent variable/feature?

In [26]:
last_10=data.X[-10:,:]
print(last_10)

[[6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]


In [27]:
mean_10= np.mean(last_10, axis=0)

features_names=data.features[:]

for i in range(len(features_names)):
    print(f'{features_names[i]},:{mean_10[i]}')



feat_0,:6.450000000000001
feat_1,:3.0300000000000002
feat_2,:5.33
feat_3,:2.17


1.4) Select all samples from the dataset with values
less than or equal to 6 for all independent
variables/features. How many samples do you obtain?

In [28]:
all_values= data.X[:,:]
condition = (all_values <= 6).all(axis=1) #condition to select the rows with all values less than 6
values_less_6= all_values[condition]
total= len(values_less_6)
print(f'Total of rows with all values less or equal than 6: {total}')


Total of rows with all values less or equal than 6: 89


 1.5) Select all samples with a class/label different
from 'Iris-setosa'. How many samples do you obtain?

In [96]:
Total_different_setosa = np.sum(data.y != "Iris-setosa")
print(Total_different_setosa)

100
